apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  namespace: default
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo
    image: debian:stable
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure