apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-example
  labels:
    app: cpu-demo
spec:
  containers:
  - name: cpu-demo
    image: vish/stress
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: "0.5"
        memory: 20Mi
    args:
      - -cpus
      - "2"