apiVersion: v1
kind: Service
metadata:
  name: my-dns-service
  namespace: default
spec:
  selector:
    name: busybox
  clusterIP: None
  ports:
  - name: foo
    port: 1234
    targetPort: 1234
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  namespace: default
  labels:
    name: busybox
spec:
  hostname: busybox-1
  subdomain: default-subdomain
  containers:
  - name: busybox1
    image: busybox:latest
    command:
        - sleep
        - "3600"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: default-subdomain
  containers:
  - name: busybox2
    image: busybox:latest
    command:
        - sleep
        - "3600"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
   