apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: busybox:stable
    command: ['sh', '-c', 'date && sleep 3600']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  initContainers:
    - name: init-container
      image: busybox:stable
      command: ['sh',  '-c', 'date && sleep 10']


  