apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-2
  labels:
    name: lifecycle-2
spec:
  containers:
  - name: lifecycle-2
    image: nginx:latest
    lifecycle:
      preStop: 
        exec:
          command: ["/bin/sh", "-c", "nginx -s quite"]
    resources:
     limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
     - containerPort: 80
       
           