apiVersion: v1
kind: Pod
metadata:
  labels:
    test: livess
  name: liveness-exec
spec:
  containers:
  - name: livess
    image: busybox:stable
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy/; sleep 600
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5